export enum Toolbar {
  DELETE = "DELETE",
  RESIDENTIAL = "RESIDENTIAL",
  HOSPITAL = "HOSPITAL",
  SCHOOL = "SCHOOL",
  CURSOR = "CURSOR",
  SEWAGE_TREATMENT = "SEWAGE_TREATMENT",
  WATER_SUPPLY = "WATER_SUPPLY",
  ADMINISTRATION = "ADMINISTRATION",
  ELECTRICITY = "ELECTRICITY",
  COMMERCIAL = "COMMERCIAL",
  INDUSTRIAL = "INDUSTRIAL",
  ROAD = "ROAD"
}
