export const STATE_CODES = {
  "Andaman And Nicobar Islands": 35,
  "Andhra Pradesh": 28,
  "Arunachal Pradesh": 12,
  Assam: 18,
  Bihar: 10,
  Chhattisgarh: 22,
  Goa: 30,
  Gujarat: 24,
  Haryana: 6,
  "Himachal Pradesh": 2,
  "Jammu And Kashmir": 1,
  Jharkhand: 20,
  Karnataka: 29,
  Kerala: 32,
  Ladakh: 37,
  Lakshadweep: 31,
  "Madhya Pradesh": 23,
  Maharashtra: 27,
  Manipur: 14,
  Meghalaya: 17,
  Mizoram: 15,
  Nagaland: 13,
  Odisha: 21,
  Puducherry: 34,
  Punjab: 3,
  Rajasthan: 8,
  Sikkim: 11,
  "Tamil Nadu": 33,
  Telangana: 36,
  "The Dadra And Nagar Haveli And Daman And Diu": 38,
  Tripura: 16,
  Uttarakhand: 5,
  "Uttar Pradesh": 9,
  "West Bengal": 19,
  TELANGANA: 36,
  "ANDHRA PRADESH": 37,
  "OTHER TERRITORY": 97,
  "OTHER COUNTRY": 96,
};

export const REVERSE_STATE_CODE = {
  35: "Andaman And Nicobar Islands",
  28: "Andhra Pradesh",
  12: "Arunachal Pradesh",
  18: "Assam",
  10: "Bihar",
  22: "Chhattisgarh",
  30: "Goa",
  24: "Gujarat",
  6: "Haryana",
  2: "Himachal Pradesh",
  1: "Jammu And Kashmir",
  20: "Jharkhand",
  29: "Karnataka",
  32: "Kerala",
  37: "Ladakh",
  31: "Lakshadweep",
  23: "Madhya Pradesh",
  27: "Maharashtra",
  14: "Manipur",
  17: "Meghalaya",
  15: "Mizoram",
  13: "Nagaland",
  21: "Odisha",
  34: "Puducherry",
  3: "Punjab",
  8: "Rajasthan",
  11: "Sikkim",
  33: "Tamil Nadu",
  36: "Telangana",
  38: "The Dadra And Nagar Haveli And Daman And Diu",
  16: "Tripura",
  5: "Uttarakhand",
  9: "Uttar Pradesh",
  19: "West Bengal",
};
