/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/commercial/scene.glb -o src/components/models/commercial.jsx 
Author: Zeeshan Khan (https://sketchfab.com/zeekhan733)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-store-building-a26a5528823945a99386a34d92313f6c
Title: Low Poly Store Building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CommercialModel(props) {
  const { nodes, materials } = useGLTF('commercial/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={51.446}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.typeMesh2_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
          <mesh geometry={nodes.typeMesh2_lambert2_0.geometry} material={materials.lambert2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('commercial/scene.glb')
