/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/electric_facility/scene.glb -o src/components/models/electric_facility.jsx 
Author: Fishboe (https://sketchfab.com/ministephen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-factory-a5e53371d0804162bd45cf05956da358
Title: Low Poly Factory
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ElectricityModel(props) {
  const { nodes, materials } = useGLTF("/electric_facility/scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[3.51, 1, 0]}
      />
    </group>
  );
}

useGLTF.preload("/electric_facility/scene.glb");
