/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 assets/hospital_health/1.glb -o src/components/models/hospital1.jsx 
Author: linus1178 (https://sketchfab.com/linus1178)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hospital-72e26a3f5a5548e09485496af1e3f9ae
Title: hospital
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hospital1Model(props) {
  const { nodes, materials } = useGLTF("/hospital_health/1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/hospital_health/1.glb");
