/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 assets/residential/house-2.glb -o src/components/models/house2.jsx 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function House2Model(props) {
  const { nodes, materials } = useGLTF("/residential/house-2.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Houses_SecondAge_3_Level3_1.geometry}
          material={materials.Main}
        />
        <mesh
          geometry={nodes.Houses_SecondAge_3_Level3_2.geometry}
          material={materials.Walls}
        />
        <mesh
          geometry={nodes.Houses_SecondAge_3_Level3_3.geometry}
          material={materials.Stone}
        />
        <mesh
          geometry={nodes.Houses_SecondAge_3_Level3_4.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Houses_SecondAge_3_Level3_5.geometry}
          material={materials.Wood_Light}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/residential/house-2.glb");
