/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/industrial/factory.glb -o src/components/models/industrial.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function IndustrialModel(props) {
  const { nodes, materials } = useGLTF('industrial/factory.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-38.909, 0, 0]} scale={[0.725, 1.38, 0.725]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials.grey} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube016_3.geometry} material={materials['Material glass']} />
        <mesh geometry={nodes.Cube016_4.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-47.566, 0, 6.361]} scale={[4.68, 1, 4.68]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.grey} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube019_4.geometry} material={materials.black} />
      </group>
      <group position={[25.06, 0, 0]} scale={0.835}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube005_4.geometry} material={materials.black} />
        <mesh geometry={nodes.Cube005_5.geometry} material={materials.grey} />
      </group>
    </group>
  )
}

useGLTF.preload('industrial/factory.glb')
